
version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - host
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=vitocox18
    volumes:
      - mongodb-data

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - host
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=vitocox18
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=vitocox18

  flask-app:
    build: .
    ports: 
      - 5000:5000
    volumes:
      - .:/app
    networks:
      - host
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=vitocox18
    depends_on:
      - mongo

networks:
    host:

volumes:
  mongodb-data:
