version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27018:27017
    command: mongod --config /etc/mongod.conf
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=vitocox18
      - MONGO_INITDB_DATABASE=labels
    volumes:
      - ./mongodb-data:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - labels_api_network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=vitocox18
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=vitocox18
    networks:
      - labels_api_network

  flask-app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=vitocox18
    depends_on:
      - mongo
    networks:
      - labels_api_network

networks:
  labels_api_network:
    driver: bridge
